### ISSUE TITLE
字体依然是转换成了rem

### ISSUE THREAD

**Issue by WTBF** [Mrluobo/fis3-preprocessor-px2rem#1]
.box {
  width: 4rem;
  height: 2.666667rem;
  font-size: 0.4rem;
}

**Comment by Mrluobo** [comment]
如果你想  转换为  根据dpr的 的 像素的话  在  `font-size: 18px;`里面加上`/*px*/`注释就好了。
如果单纯的想保留  像素的话  后面加 `/*no*/`
